In [1]:
import pandas as pd 
import numpy as np

In [19]:
data=pd.read_csv("D:/Ds Csv files Assignment/hypothesis/BuyerRatio.csv")
data 

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [20]:
data.drop(['Observed Values'],axis=1,inplace=True)


In [21]:
data

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [22]:
import scipy.stats as stats 
from scipy.stats import chi2_contingency 

In [23]:
p_value=stats.chi2_contingency(data)

In [24]:
p_value

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [25]:
p_value[1]

0.6603094907091882

# Costomer+OrderForm

In [4]:
import pandas as pd 
import numpy as np
from scipy import stats

In [5]:
df=pd.read_csv('Costomer+OrderForm.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'Costomer+OrderForm.csv'

In [ ]:
df.Phillippines.value_counts()

In [ ]:
df.Indonesia.value_counts()

In [ ]:
df.Malta.value_counts()

In [6]:
df.India.value_counts()

NameError: name 'df' is not defined

In [7]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [8]:
# Make a contingency table
df1=np.array([[271,267,269,280],[29,33,31,20]])
df1

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [9]:
# Chi2 contengency independence test
chi2_contingency(df1)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

# Cutlet

In [10]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [11]:
df=pd.read_csv("Cutlets.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'Cutlets.csv'

In [12]:
df.head()

NameError: name 'df' is not defined

In [13]:
UnitA=pd.Series(df.iloc[:,0])
UnitA

NameError: name 'df' is not defined

In [14]:
UnitB=pd.Series(df.iloc[:,1])
UnitB

NameError: name 'df' is not defined

In [15]:
# 2-sample 2-tail ttest:   
p_value=stats.ttest_ind(UnitA,UnitB)
p_value

NameError: name 'UnitA' is not defined

# LabTAT

In [16]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [17]:
df=pd.read_csv('LabTAT.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'LabTAT.csv'

In [18]:
# Anova ftest statistics: 
p_value=stats.f_oneway(df.iloc[:,0],df.iloc[:,1],df.iloc[:,2],df.iloc[:,3])
p_value

NameError: name 'df' is not defined